# File di configurazione API Geteway, ascolta tutte le richieste esterne sulla porta 80
# e le smista al giusto microservizio (user manager o data collector) che si trovano nella rete interna di docker


server {
    #configuro la porta d'ascolto
    listen 80;
    #definisco il nome del server (nel nostro caso serve a poco non essendo un "dominio" pubblico/reale)
    server_name localhost;

    #Routing verso lo user manager
    #inoltra tutte le richieste che iniziano con /users allo user manager
    location /users {
        #inoltra la richiesta direttamente al container "user_manager" sulla porta 5000.
        proxy_pass http://user_manager:5000;
    }
    #Routing verso il data collector sulla porta 5001
    # Interessi
    location /interests {
        proxy_pass http://data_collector:5001;
    }

    # Voli
    location /flights {
        proxy_pass http://data_collector:5001;
    }

    # Statistiche
    location /statistics {
        proxy_pass http://data_collector:5001;
    }
}