# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0buserservice\"\x1c\n\x0bUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"5\n\x12\x43redentialsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\x0cUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\xaa\x01\n\x0bUserManager\x12\x46\n\x0f\x43heckUserExists\x12\x18.userservice.UserRequest\x1a\x19.userservice.UserResponse\x12S\n\x15VerifyUserCredentials\x12\x1f.userservice.CredentialsRequest\x1a\x19.userservice.UserResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=27
  _USERREQUEST._serialized_end=55
  _CREDENTIALSREQUEST._serialized_start=57
  _CREDENTIALSREQUEST._serialized_end=110
  _USERRESPONSE._serialized_start=112
  _USERRESPONSE._serialized_end=142
  _USERMANAGER._serialized_start=145
  _USERMANAGER._serialized_end=315
# @@protoc_insertion_point(module_scope)
