services:
  # 1.DB UTENTI (PostgreSQL)
  postgres_container:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2.DB DATI (MongoDB)
  mongo_container:
    image: mongo:latest
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  #3.USER MANAGER
  user_manager:
    build:
      context: .
      dockerfile: user_manager/Dockerfile
    container_name: user_manager
    ports:
      - "5000:5000"
      - "50051:50051"
    depends_on:
      - postgres_container
    environment:
      - PYTHONUNBUFFERED=1

  # 4.DATA COLLECTOR
  data_collector:
    build:
      context: .
      dockerfile: data_collector/Dockerfile
    container_name: data_collector
    ports:
      - "5001:5001"
    depends_on:
      - user_manager
      - mongo_container
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
  mongo_data: