#Questo file contiene tutte le informazioni sensibili che NON devono essere
#scritte in chiaro nel codice (hardcoded) o nelle ConfigMap.
#Kubernetes memorizza questi dati codificati in Base64.
#Vengono decodificati e iniettati nei container solo al momento dell'avvio,
#come variabili d'ambiente.

apiVersion: v1
kind: Secret
metadata:
  name: homework3-dsbd-secrets
type: Opaque

#Usiamo "stringData" invece che "data" così noi scriviamo le password in chiaro.
#Kubernetes le codifica automaticamente in Base64.
#Se avessimo usato "data", le avremmo dovute scrivere noi già codificate.
stringData:
  # Credenziali Database PostgreSQL e Mongo (Passwords)
  PG_PASS: "postgrespassword"
  mongo-root-password: "adminpassword"

  #URI di connessione completo per MongoDB.
  #Lo mettiamo qui (e non nel ConfigMap) perché contiene la password in chiaro
  MONGO_URI: "mongodb://admin:adminpassword@mongo-service:27017/data_db?authSource=admin"



  #Sono le credenziali per l'API OpenSky. che prima erano contenute nel file credentials.json
  #Servono al Data Collector per autenticarsi alle API di OpenSky.
  #opensky-client-id: "nappopippo2-api-client"
  #opensky-client-secret: "sU4T2awOdz7J1gHw2g5ub9919GXpvIYR"

  #opensky-client-id: "giovanni07-api-client"
  #opensky-client-secret: "ykTJUUoJkF7CBWRHJRz63asTSEYdje1Q"

  opensky-client-id: "alessia_tomarchio@outlook.it-api-client"
  opensky-client-secret: "4QW3KwcMQ0yWbQoHcLM8K295rvqkHioQ"

  #Credenziali per l'invio delle email di allerta.
  #Identiche a quelle utilizzate nel secondo homework.
  #Dove usiamo una "Password per le App" invece che la vera password di gmail.
  SENDER_EMAIL: "giovannicontarino@gmail.com"
  SENDER_PASSWORD: "esrtxsgsfkyrraxs"